trigger:
    - "*"
pr:
    - "*"

strategy:
    matrix:
        linux:
            imageName: "ubuntu-20.04"
        mac:
            imageName: "macOS-11"
        windows:
            imageName: "windows-2022"

pool:
    vmImage: $(imageName)

steps:
    - task: NodeTool@0
      inputs:
          versionSpec: "12.x"
      displayName: "Install Node.js"

    - bash: |
          /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
          echo ">>> Started xvfb"
      displayName: Start xvfb
      condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

    - bash: |
          npm install
          npm run build
      displayName: Build

    - bash: |
          npm test
      displayName: Run Tests
      env:
          DISPLAY: ":99.0"
